spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/SpringCloud_user?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 119.29.243.22
    port: 6379
  jpa:
    show-sql: true
  http:
    encoding:
      charset: utf-8
feign:
  hystrix:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
