spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://127.0.0.1/SpringCloud_product?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  http:
    encoding:
      charset: utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
feign:
  hystrix:
    enabled: false
