spring:
  application:
    name: config-server
  http:
    encoding:
      charset: utf-8
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huluobo11/spring-cloud-demo.git
          username: 15136129644@139.com
          password: guai1174963032
          search-paths: config-repo
          force-pull: true
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 119.29.243.22
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084
feign:
  hystrix:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
